[package]
name = "turn-tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.6.10"
actix-governor = "0.10.0"
actix-web = "4"
actix-ws = "0.4.0"
dashmap = "6.2.1"
env_logger = "0.11.10"
futures-util = "0.3.32"
log = "0.4.32"
rand = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "sync", "time"] }

[dev-dependencies]
actix-rt = "2.11.0"
awc = "3.8.2"
futures-util = "0.3.32"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
missing_docs_in_private_items = "allow"
separated_literal_suffix = "allow"
implicit_return = "allow"
print_stderr = "allow"
exhaustive_enums = "allow"
exhaustive_structs = "allow"
single_char_lifetime_names = "allow"
missing_inline_in_public_items = "allow"
self_named_module_files = "allow"
wildcard_enum_match_arm = "allow"
pattern_type_mismatch = "allow"
std_instead_of_core = "allow"
